name: dt-atari
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.4
  - mysql=5.7.24
  - numpy=1.26.4
  - pip=23.3.1
  - python=3.10.14
  - pip:
      - atari-py==0.2.9
      - opencv-python==4.9.0.80
      - torch==2.3.0
